export {
  ItemRepository,
  itemSlug,
  itemVisibilities,
  normalizeItemVisibility,
  normalizeTagName,
  type CreateItemCoreInput,
  type ItemCoreRecord,
  type UpdateItemCoreInput,
  type ItemTransaction,
  type ItemVisibility,
  ItemPolicyError,
  type ItemPolicyCode,
} from './item-repository.js';
export {
  ItemAccessError,
  ItemCreateError,
  ItemService,
  ItemVersionConflictError,
  type CreatedItem,
  type CreateItemInput,
  type CreateItemOutcome,
  type ItemAccessErrorCode,
  type ItemCreateErrorCode,
  type ItemDetail,
  type ItemMutationMetadata,
  type ItemUpdateMetadata,
  type SafeDiffEntry,
  type UpdatedItem,
  type UpdateItemInput,
  type UpdateItemOutcome,
} from './item-service.js';
export {
  creationInvalidation,
  itemInvalidatorEvents,
  itemInvalidatorRegistry,
  planItemInvalidation,
  type ItemChangeSignals,
  type ItemInvalidationPlan,
  type ItemInvalidatorEntry,
  type ItemInvalidatorEvent,
  type SynchronousProjectionScope,
} from './item-invalidation.js';
export {
  CatalogDictionaryRepository,
  type CategoryRecord,
  type DictionaryMutationMetadata,
  type LifecycleStatusRecord,
} from './dictionary-repository.js';
export {
  CatalogDictionaryAuthorizationError,
  CatalogDictionaryService,
  type DictionaryRequestMetadata,
  type DisplayNamePreview,
} from './dictionary-service.js';
export {
  DictionaryPolicyError,
  normalizeDisplayTemplate,
  normalizeLabels,
  rejectKeyMutation,
  semanticColorTokenPattern,
  stableDictionaryKeyPattern,
  validateColorToken,
  validateDisplayOrder,
  validateExpectedVersion,
  validateStableKey,
  type DictionaryPolicyCode,
  type LocalizedLabel,
} from './dictionary-policy.js';
export { CatalogMediaOwnerAdapter } from './media-owner-adapter.js';
