const interactive = {
  accessibility: ['keyboard', 'focus-visible', 'touch-target', 'reduced-motion', 'zoom-200'],
};

export const facadeContracts = {
  AppButton: {
    props: ['disabled', 'loading', 'variant'],
    events: ['click'],
    slots: ['default'],
    states: ['default', 'loading', 'disabled'],
    ...interactive,
  },
  AppInput: {
    props: ['modelValue', 'disabled', 'invalid', 'describedBy'],
    events: ['update:modelValue'],
    slots: [],
    states: ['default', 'validation', 'disabled'],
    ...interactive,
  },
  AppTextarea: {
    props: ['modelValue', 'disabled', 'invalid', 'describedBy'],
    events: ['update:modelValue'],
    slots: [],
    states: ['default', 'validation', 'disabled'],
    ...interactive,
  },
  AppSelect: {
    props: ['modelValue', 'options', 'disabled', 'invalid'],
    events: ['update:modelValue'],
    slots: ['option'],
    states: ['default', 'empty', 'validation', 'disabled'],
    ...interactive,
  },
  AppMultiSelect: {
    props: ['modelValue', 'options', 'disabled', 'invalid'],
    events: ['update:modelValue'],
    slots: ['option'],
    states: ['default', 'empty', 'validation', 'disabled'],
    ...interactive,
  },
  AppDateField: {
    props: ['modelValue', 'disabled', 'invalid'],
    events: ['update:modelValue'],
    slots: [],
    states: ['default', 'validation', 'disabled'],
    ...interactive,
  },
  AppMoneyField: {
    props: ['modelValue', 'currency', 'disabled', 'invalid'],
    events: ['update:modelValue'],
    slots: [],
    states: ['default', 'validation', 'disabled'],
    ...interactive,
  },
  AppField: {
    props: ['label', 'error', 'inputId'],
    events: [],
    slots: ['default'],
    states: ['default', 'error'],
    ...interactive,
  },
  AppFormSection: {
    props: ['title', 'disabled'],
    events: [],
    slots: ['default'],
    states: ['default', 'disabled'],
    ...interactive,
  },
  AppTable: {
    props: ['rows', 'loading'],
    events: ['rowSelect'],
    slots: ['default', 'empty', 'loading'],
    states: ['default', 'loading', 'empty', 'error', 'responsive'],
    ...interactive,
  },
  AppDataView: {
    props: ['items', 'loading'],
    events: [],
    slots: ['list', 'grid', 'empty'],
    states: ['default', 'loading', 'empty', 'error', 'responsive'],
    ...interactive,
  },
  AppDialog: {
    props: ['visible', 'title'],
    events: ['update:visible'],
    slots: ['default', 'footer'],
    states: ['default', 'error'],
    ...interactive,
  },
  AppDrawer: {
    props: ['visible', 'title'],
    events: ['update:visible'],
    slots: ['default'],
    states: ['default', 'responsive'],
    ...interactive,
  },
  AppMenu: {
    props: ['items'],
    events: ['select'],
    slots: ['item'],
    states: ['default', 'empty', 'responsive'],
    ...interactive,
  },
  AppToast: {
    props: ['position'],
    events: [],
    slots: ['message'],
    states: ['default', 'error'],
    accessibility: ['screen-reader', 'reduced-motion', 'zoom-200'],
  },
  AppBreadcrumb: {
    props: ['items', 'home'],
    events: [],
    slots: ['item'],
    states: ['default', 'responsive'],
    ...interactive,
  },
  AppFileUpload: {
    props: ['accept', 'disabled', 'loading'],
    events: ['select', 'remove'],
    slots: ['empty'],
    states: ['default', 'loading', 'empty', 'error', 'disabled'],
    ...interactive,
  },
  AppPagination: {
    props: ['first', 'rows', 'totalRecords', 'disabled'],
    events: ['update:first'],
    slots: [],
    states: ['default', 'disabled', 'responsive'],
    ...interactive,
  },
};
