/** Public backend surface. Feature modules export only deliberate entry points here. */
export function foundationStatus(): { status: string } {
  return { status: 'ready' };
}

export {
  createDatabase,
  currentSchemaVersion,
  expectedSchemaVersion,
  migrateToLatest,
} from './database.js';
export {
  createSettingsClient,
  initializeInstallationSettings,
  readAdminAuthorizationSettings,
} from './settings.repository.js';
export {
  bootstrapFirstOwner,
  AuthAdministrationError,
  AuthAdministrationService,
  AuthRateLimiter,
  can,
  canManageRole,
  capabilities,
  FirstOwnerBootstrapError,
  PasswordHasher,
  permissionsFor,
  RateLimitError,
  roles,
  SessionError,
  SessionService,
  sessionPolicy,
  type BootstrappedOwner,
  type FirstOwnerBootstrapInput,
  type AuthenticatedSession,
  type ActorRole,
  type AuditMetadata,
  type AuthorizationSettings,
  type Capability,
  type InvitationSummary,
  type IssuedSession,
  type Role,
  type SessionActor,
  type SessionRequestMetadata,
  type SessionSummary,
  type UserSummary,
} from './auth/index.js';
export {
  CatalogDictionaryRepository,
  CatalogDictionaryAuthorizationError,
  CatalogDictionaryService,
  DictionaryPolicyError,
  normalizeDisplayTemplate,
  normalizeLabels,
  rejectKeyMutation,
  semanticColorTokenPattern,
  stableDictionaryKeyPattern,
  validateColorToken,
  validateDisplayOrder,
  validateExpectedVersion,
  validateStableKey,
  type CategoryRecord,
  type DictionaryMutationMetadata,
  type DictionaryPolicyCode,
  type DictionaryRequestMetadata,
  type LifecycleStatusRecord,
  type LocalizedLabel,
} from './catalog/index.js';
export {
  AttributeValidationError,
  canonicalizeFieldValues,
  compareDecimal,
  conversionLossless,
  conversionSupported,
  currencyPattern,
  decimal,
  fieldDataTypes,
  FieldDefinitionRepository,
  FieldDefinitionService,
  fieldScopes,
  fieldValueSlots,
  fieldVisibilities,
  normalizeDefaultValue,
  normalizeLocalizedText,
  normalizeOptionalLocalizedText,
  normalizeUnit,
  normalizeValidationRules,
  parseCalendarDate,
  parseInstant,
  planAttributeRows,
  projectFieldValues,
  reindexReasons,
  reindexWarning,
  SchemaAuthorizationError,
  SchemaPolicyError,
  scopeForOwner,
  stableFieldKeyPattern,
  TransactionalAttributeValuePort,
  usesOptions,
  validateCanonicalValues,
  validateDataType,
  validateRepeatable,
  validateScope,
  validateVisibility,
  validationRuleNamesFor,
  valueSlotsFor,
  type ApplicableFieldDefinition,
  type AttributeIssue,
  type AttributeIssueCode,
  type AttributeOwner,
  type AttributeValueAssignment,
  type AttributeValuePort,
  type CanonicalFieldValue,
  type ConversionPreview,
  type CreateFieldDefinitionInput,
  type FieldDataType,
  type FieldDefinitionMutation,
  type FieldDefinitionRecord,
  type FieldOptionMembership,
  type FieldOptionRecord,
  type FieldScope,
  type FieldValueShape,
  type FieldValueSlot,
  type FieldVisibility,
  type LocalizedText,
  type PlannedAttributeRow,
  type ReindexReason,
  type ReindexWarning,
  type ReplaceAttributeValues,
  type SchemaMutationMetadata,
  type SchemaPolicyCode,
  type SchemaRequestMetadata,
  type UpdateFieldDefinitionInput,
  type ValidationRules,
} from './schema/index.js';
export {
  TransactionalAuditPort,
  TransactionalOutboxPort,
  type AuditPort,
  type AuditRecord,
  type OutboxMessage,
  type OutboxPort,
  type TransactionContext,
} from './infrastructure/index.js';
export { lifecycleStatusSeeds, runSeeds, seedLifecycleStatuses } from './seed.js';
