/** Public backend surface. Feature modules export only deliberate entry points here. */
export function foundationStatus(): { status: string } {
  return { status: 'ready' };
}

export {
  createDatabase,
  currentSchemaVersion,
  expectedSchemaVersion,
  migrateToLatest,
} from './database.js';
export {
  createSettingsClient,
  initializeInstallationSettings,
  readAdminAuthorizationSettings,
} from './settings.repository.js';
export {
  bootstrapFirstOwner,
  AuthAdministrationError,
  AuthAdministrationService,
  AuthRateLimiter,
  can,
  canManageRole,
  capabilities,
  FirstOwnerBootstrapError,
  PasswordHasher,
  permissionsFor,
  RateLimitError,
  roles,
  SessionError,
  SessionService,
  sessionPolicy,
  type BootstrappedOwner,
  type FirstOwnerBootstrapInput,
  type AuthenticatedSession,
  type ActorRole,
  type AuditMetadata,
  type AuthorizationSettings,
  type Capability,
  type InvitationSummary,
  type IssuedSession,
  type Role,
  type SessionActor,
  type SessionRequestMetadata,
  type SessionSummary,
  type UserSummary,
} from './auth/index.js';
export {
  CatalogDictionaryRepository,
  CatalogDictionaryAuthorizationError,
  CatalogDictionaryService,
  DictionaryPolicyError,
  normalizeDisplayTemplate,
  normalizeLabels,
  rejectKeyMutation,
  semanticColorTokenPattern,
  stableDictionaryKeyPattern,
  validateColorToken,
  validateDisplayOrder,
  validateExpectedVersion,
  validateStableKey,
  type CategoryRecord,
  type DictionaryMutationMetadata,
  type DictionaryPolicyCode,
  type DictionaryRequestMetadata,
  type DisplayNamePreview,
  type LifecycleStatusRecord,
  type LocalizedLabel,
} from './catalog/index.js';
export {
  ItemRepository,
  itemSlug,
  itemVisibilities,
  normalizeItemVisibility,
  normalizeTagName,
  type CreateItemCoreInput,
  type ItemCoreRecord,
  type ItemTransaction,
  type ItemVisibility,
  type UpdateItemCoreInput,
  ItemPolicyError,
  type ItemPolicyCode,
  ItemAccessError,
  ItemCreateError,
  ItemService,
  ItemVersionConflictError,
  creationInvalidation,
  itemInvalidatorEvents,
  itemInvalidatorRegistry,
  planItemInvalidation,
  type CreatedItem,
  type CreateItemInput,
  type CreateItemOutcome,
  type ItemAccessErrorCode,
  type ItemChangeSignals,
  type ItemCreateErrorCode,
  type ItemDetail,
  type ItemInvalidationPlan,
  type ItemInvalidatorEntry,
  type ItemInvalidatorEvent,
  type ItemMutationMetadata,
  type ItemUpdateMetadata,
  type SafeDiffEntry,
  type SynchronousProjectionScope,
  type UpdatedItem,
  type UpdateItemInput,
  type UpdateItemOutcome,
} from './catalog/index.js';
export {
  AttributeValidationError,
  canonicalizeFieldValues,
  compareDecimal,
  coreDisplayTokens,
  conversionLossless,
  describeDisplayTokens,
  displayTemplateDataTypes,
  displayTemplateLimits,
  displayTemplateTokens,
  DisplayTemplateError,
  parseDisplayTemplate,
  renderDisplayName,
  toDisplayTokenField,
  validateDisplayTemplate,
  type CoreDisplayToken,
  type DisplayNameSource,
  type DisplayTemplateIssue,
  type DisplayTemplateIssueCode,
  type DisplayTemplateSegment,
  type DisplayTokenDescription,
  type DisplayTokenField,
  conversionSupported,
  currencyPattern,
  decimal,
  fieldDataTypes,
  FieldDefinitionRepository,
  FieldDefinitionService,
  fieldScopes,
  fieldValueSlots,
  fieldVisibilities,
  normalizeDefaultValue,
  normalizeLocalizedText,
  normalizeOptionalLocalizedText,
  normalizeUnit,
  normalizeValidationRules,
  parseCalendarDate,
  parseInstant,
  planAttributeRows,
  projectFieldValues,
  reindexReasons,
  reindexWarning,
  SchemaAuthorizationError,
  SchemaPolicyError,
  scopeForOwner,
  stableFieldKeyPattern,
  TransactionalAttributeValuePort,
  usesOptions,
  validateCanonicalValues,
  validateDataType,
  validateRepeatable,
  validateScope,
  validateVisibility,
  validationRuleNamesFor,
  valueSlotsFor,
  type ApplicableFieldDefinition,
  type AttributeIssue,
  type AttributeIssueCode,
  type AttributeOwner,
  type AttributeValueAssignment,
  type AttributeValuePort,
  type CanonicalFieldValue,
  type ConversionPreview,
  type CreateFieldDefinitionInput,
  type FieldDataType,
  type FieldDefinitionMutation,
  type FieldDefinitionRecord,
  type FieldOptionMembership,
  type FieldOptionRecord,
  type FieldScope,
  type FieldValueShape,
  type FieldValueSlot,
  type FieldVisibility,
  type LocalizedText,
  type PlannedAttributeRow,
  type ReindexReason,
  type ReindexWarning,
  type ReplaceAttributeValues,
  type SchemaMutationMetadata,
  type SchemaPolicyCode,
  type SchemaRequestMetadata,
  type UpdateFieldDefinitionInput,
  type ValidationRules,
} from './schema/index.js';
export {
  IdempotencyRepository,
  idempotencyPolicy,
  requestFingerprint,
  TransactionalIdempotencyPort,
  TransactionalMovementHistoryPort,
  TransactionalSearchProjectionPort,
  TransactionalAuditPort,
  TransactionalOutboxPort,
  type IdempotencyCompletion,
  type IdempotencyPort,
  type ItemSearchProjection,
  type MovementHistoryPort,
  type MovementRecord,
  type SearchProjectionPort,
  type AuditPort,
  type AuditRecord,
  type OutboxMessage,
  type OutboxPort,
  type TransactionContext,
  type IdempotencyReservation,
  type IdempotencyReservationPort,
  type ReserveIdempotencyRequest,
} from './infrastructure/index.js';
export { CatalogMediaOwnerAdapter } from './catalog/index.js';
export {
  createJobRuntime,
  createMediaRuntime,
  imageProcessingLimits,
  type MediaRuntime,
} from './runtime.js';
export {
  backoffDelayMs,
  createBackgroundRuntime,
  defaultOutboxRoutes,
  JobPermanentError,
  JobRepository,
  JobRunner,
  jobPolicy,
  jobStates,
  jobTypes,
  maximumMediaConcurrency,
  mediaProcessingRoute,
  nextFailureState,
  normalizeProgress,
  OutboxDispatcher,
  type BackgroundRuntime,
  type BackgroundRuntimeOptions,
  type DispatchSummary,
  type EnqueueJobInput,
  type JobContext,
  type JobHandler,
  type JobLogger,
  type JobRecord,
  type JobRunnerOptions,
  type JobSchedule,
  type JobState,
  type JobType,
  type JobTypePolicy,
  type MediaBackgroundPorts,
  type OutboxMessageRow,
  type OutboxRoute,
} from './jobs/index.js';
export {
  approvedImageMimeTypes,
  assetStorageKey,
  ChildImageProcessor,
  classifyChildFailure,
  defaultCapabilityFixtureRoot,
  ImageProcessingError,
  isForbiddenMetadataField,
  JobLeaseLostError,
  mediaCapabilityFixtures,
  MediaProcessingService,
  metadataPolicy,
  orientedDimensions,
  parseHeaderFields,
  plannedVariants,
  resourceLimitedCommand,
  spawnLimitedChild,
  stripWebpMetadata,
  uprightDimensions,
  variantNames,
  webpMetadataChunks,
  WebpContainerError,
  variantPlan,
  variantStorageKey,
  detectImageSignature,
  fileExtension,
  LocalMediaStorage,
  mediaLimits,
  MediaAccessError,
  MediaPolicyError,
  MediaRepository,
  mediaRelationRoles,
  MediaService,
  MediaStorageLimitError,
  MediaVersionConflictError,
  mediaVisibilities,
  normalizeAltText,
  normalizeUploadFilename,
  requireExtensionAgreement,
  temporaryUploadKey,
  validateDeclaredByteSize,
  validateMimeType,
  validateOrderedIds,
  validateRole,
  validateMediaVisibility,
  verifyReceivedUpload,
  type ApprovedImageMimeType,
  type AttachedMedia,
  type BeginUploadInput,
  type CapabilityFixture,
  type CapabilityReport,
  type CapabilityResult,
  type ChildLauncher,
  type ChildOutcome,
  type ImageProbe,
  type ImageProcessingCode,
  type ImageProcessingLimits,
  type ImageProcessorPort,
  type MaterializedObject,
  type MediaProcessingLogger,
  type MediaVariantInput,
  type MediaVariantRecord,
  type MediaVariantView,
  type ProcessAssetOutcome,
  type RenderRequest,
  type RenderedVariant,
  type VariantDefinition,
  type VariantName,
  type MediaAccessErrorCode,
  type MediaAssetRecord,
  type MediaOwner,
  type MediaOwnerPort,
  type MediaPolicyCode,
  type MediaRelationRecord,
  type MediaRelationRole,
  type MediaRequestMetadata,
  type MediaStoragePort,
  type MediaTransaction,
  type MediaView,
  type MediaVisibility,
  type StoredUpload,
  type UploadSessionRecord,
  type UploadSessionState,
  type UploadSessionView,
} from './media/index.js';
export { lifecycleStatusSeeds, runSeeds, seedLifecycleStatuses } from './seed.js';
