export {
  TransactionalIdempotencyPort,
  TransactionalMovementHistoryPort,
  TransactionalSearchProjectionPort,
  TransactionalAuditPort,
  TransactionalOutboxPort,
  type IdempotencyCompletion,
  type IdempotencyPort,
  type ItemSearchProjection,
  type MovementHistoryPort,
  type MovementRecord,
  type SearchProjectionPort,
  type AuditPort,
  type AuditRecord,
  type OutboxMessage,
  type OutboxPort,
  type TransactionContext,
} from './transaction-ports.js';
